name: Python Tests

on:
  push:
jobs:
  test:
    name: Python 2 and 3 tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 2
        uses: actions/setup-python@v2
        with:
          python-version: 2.7.18
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 
      - name: Run Python 2 tests
        run: python2 -m unittest discover
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 
      - name: Run Python 3 tests
        run: python3 -m unittest discover